[book]
authors = ["The Trane Project"]
language = "en"
multilingual = false
src = "verso_build/src"
title = "The Trane Book"

[build]
build-dir = "docs"

[output.html]
additional-css = ["custom.css"]
