baseURL = 'https://trane-project.github.io/'
languageCode = 'en-us'
title = 'The Trane Blog'
theme = 'hugotex'

[author]
  abstract = 'An automated learning system for the acquisition of complex skills'
  name = 'The Trane Project'

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'paraiso-dark' # syntax highlighting style

[Params]
  darkmode = true